- name: Tower Machine Credentials Role Playbook
  hosts: localhost
  gather_facts: no
  vars_files:
  - vars_users.yml

  tasks:
  #- name: Run Lab script
  #  import_tasks: lab_script.yml

  - name: Add credential "Operations"
    tower_credential:
      name: "Operations"
      description: "Operations Credential"
      organization: "Default"
      username: "devops"
      password: "redhat"
      become_method: "sudo"
      become_username: "root"
      become_password: "redhat"
      kind: "ssh"
      state: "present"
      tower_config_file: "{{ tower_credential_file }}"

  - name: Add credential via command Line
    shell: >
            tower-cli credential create
            --name "Operations" --organization "Default" 
            --description "Operations Credential" --credential-type "Machine"
            --tower-host "tower.lab.example.com" --tower-username "admin"
            --tower-password "redhat" --insecure
            

   
  - name: Assign permissions (role) to Operations Team
    tower_role:
      credential: "Operations"
      team: "Operations"
      role: "admin"
      state: "present"
      tower_host: "tower.lab.example.com"
      tower_username: "admin"
      tower_password: "redhat"
      validate_certs: false


  - name: Assign permissions (role) to Developers Team
    shell: > 
            tower-cli role grant 
            --team 'Developers' --credential "Operations" --type 'use'
            --tower-host "tower.lab.example.com" --tower-username "admin" 
            --tower-password "redhat" --insecure
